### ISSUE TITLE
Add additional tests for admin-client

### ISSUE THREAD

**Issue by graziang** [keycloak/keycloak-client#38]
### Description

As a follow-up of https://github.com/keycloak/keycloak/issues/31869, we need to add more tests for the admin-client from [this package](https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin) of keycloak repository to [this package](https://github.com/keycloak/keycloak-client/tree/main/testsuite/admin-client-tests/src/test/java/org/keycloak/client/testsuite) of keycloak-client repository.

With #36, `AdminClientTest, RealmTest, RealmRolesTest, `and` ClientTest` were already added.

The idea is to add the most important test classes to cover the most important use-cases and the CRUD operations of the basic admin objects.

### What tests to add

maybe UsersTest and UserTest

also some tests from authentication package: https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/authentication

the client package for client scopes, sessions, client roles: https://github.com/keycloak/keycloak/tree/main/testsuite/integration-arquillian/tests/base/src/test/java/org/keycloak/testsuite/admin/client (edited) 

maybe the GroupTest

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-client/issues/41
- [ ] https://github.com/keycloak/keycloak-client/issues/42
- [ ] https://github.com/keycloak/keycloak-client/issues/43
- [ ] https://github.com/keycloak/keycloak-client/issues/44
- [ ] https://github.com/keycloak/keycloak-client/issues/58
```

**Comment by mposolda** [comment]
Closing as all the subtasks were finished.
@graziang Thanks for the great work!
