### ISSUE TITLE
 Testing of keycloak-authz-client in keycloak-client repository #30806 

### ISSUE THREAD

**Issue by rmartinc** [keycloak/keycloak-client#46]
### Description

This is task to make sure that keycloak-authz-client is tested in [keycloak-client repository](https://github.com/keycloak/keycloak-client). It is similar to https://github.com/keycloak/keycloak/issues/30804 task, which exists for admin client. And also for https://github.com/keycloak/keycloak/issues/31978, which was already done for policy-enforcer.

I am not sure if we want to "copy" some tests or just move them and/or if we can consider moving of whole authz-client to keycloak-client repository (this is to be investigated and should be done after move of policy-enforcer). For now, we can probably copy them and then we can figure later if we are then removing them from keycloak repository and keep them just in keycloak-client repository.

Probably not all tests can be moved to the client project.

```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-client/issues/47
- [ ] https://github.com/keycloak/keycloak-client/issues/55
- [ ] https://github.com/keycloak/keycloak-client/issues/73
- [ ] https://github.com/keycloak/keycloak-client/issues/62
- [ ] https://github.com/keycloak/keycloak-client/issues/75
- [ ] https://github.com/keycloak/keycloak-client/issues/65
- [ ] https://github.com/keycloak/keycloak-client/issues/67
- [ ] https://github.com/keycloak/keycloak-client/issues/59
```

**Comment by mposolda** [comment]
Closing this issue as all the child issues done.

@rmartinc Thanks!
